apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.appName }}
spec:
  hosts:
    - "*"
  gateways:
    - "ingress"
  http:
    - match:
        - uri:
            prefix: "/ingresPathPrefixHere"
      route:
        - destination:
            port:
              number: 6666
            host: {{ .Values.appName }}