apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
    - name: {{ .Values.appName }}-port
      port: 6666
  selector:
    app: {{ .Values.appName }}
  type: NodePort